# Generated by Django 5.2.2 on 2025-06-09 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='img_url',
            field=models.CharField(default='/static/images/chenjunjie.jpg', max_length=100),
        ),
    ]
