# Generated by Django 5.2.2 on 2025-06-09 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_alter_book_img_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='type',
            new_name='book_type',
        ),
        migrations.AddField(
            model_name='book',
            name='intro',
            field=models.TextField(default='have not intro yet, idk why'),
            preserve_default=False,
        ),
    ]
